# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Days'
        # Default value if no value is explicitly provided
        default: '90'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Download Node.js
      run: curl -o node.exe https://nodejs.org/dist/latest-v0.12.x/x64/node.exe
    - name: Verify
      run: |
        $installationPath = vswhere.exe -prerelease -latest -property installationPath
        if ($installationPath -and (Test-Path "$installationPath\Common7\Tools\vsdevcmd.bat")) {
          $json = $(& "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo -arch=x64 && pwsh -Command `"Get-ChildItem env: | Select-Object Key,Value | ConvertTo-Json`"")
          if ($LASTEXITCODE -ne 0) {
            Write-Error "($LASTEXITCODE) $installationPath\Common7\Tools\vsdevcmd.bat: $json"
          } else {
            # Write-Host $json
            $($json | ConvertFrom-Json) | ForEach-Object {
              $k, $v = $_.Key, $_.Value
              Set-Content env:\"$k" "$v"
            }
          }
        }        
        & "signtool.exe verify /v /pa node.exe"
